[package]
name = "cdumay_error"
version = "0.1.0"
authors = ["CÃ©dric Dumay <cedric.dumay@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/cdumay/cdumay-error-rs"
homepage =  "https://github.com/cdumay/cdumay-error-rs"
description = """
A library to serialize and deserialize error using serde
"""

[dependencies]
cdumay_values = { git = "https://github.com/cdumay/cdumay-values-rs" }
serde = "1.0"
serde_derive = "1.0"