[package]
name = "cdumay_error"
version = "0.1.3"
authors = ["CÃ©dric Dumay <cedric.dumay@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/cdumay/cdumay-error-rs"
homepage =  "https://github.com/cdumay/cdumay-error-rs"
description = """
A library to serialize and deserialize error using serde
"""

[features]
all = []
json = ["serde_json"]
http = ["hyper", "json"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde-value = "0.5"
hyper = { version = "0.12", optional = true }
serde_json = { version = "1.0", optional = true }